name: Release

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: 'main'
      - uses: montudor/action-zip@v1
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: |
          python sort_rime_file.py
          BASEDIR=`pwd`
          FOLDER=`find ${BASEDIR} -name "電腦RIME*" -type d`
          RELEASE="${BASEDIR}/release"
          mkdir -p $RELEASE

          function create_zip() {
              SOURCE=`find ${FOLDER} -name "$1" -type d`
              cd $SOURCE
              zip -qq -r $RELEASE/$2 ./
          }

          function copy() {
              SOURCE=`find ${FOLDER} -name "$1" -type d`
              TARGET=`find ${SOURCE} -name "$2" -type f`
              cp $TARGET $RELEASE
          }

          create_zip "注音洋蔥純注音版_*" "bopomo_onion.zip"

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          path: |
            .\release\*
   
